version: "3.2"
services:
  glucoseDB:
    image: postgres   
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: glucose-check-db
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data